all:
	g++ -g -o videoplayer main.cpp VideoPlayer.cpp -lavcodec -I/usr/include/libavcodec -lavformat -I/usr/include/libavformat/ -lavutil -I/usr/include/libavutil -lsfml-system -lsfml-window -lsfml-graphics
